梳理了往 gogs 里导入项目，以及初始化 nexus 的安装器 installer 逻辑

diff --git a/templates/cicd-installer.yaml b/templates/cicd-installer.yaml
--- a/templates/cicd-installer.yaml
+++ b/templates/cicd-installer.yaml
@@ -1,7 +1,9 @@
 apiVersion: v1
 kind: ServiceAccount
 metadata:
-    name: cicd_installer
+  name: cicd_installer
+  labels:
+    app: installer
 
 ---
 
@@ -10,6 +12,8 @@ kind: RoleBinding
 groupNames: null
 metadata:
   name: cicd_installer_admin
+  labels:
+    app: installer
 roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
@@ -18,15 +22,107 @@ subjects:
   - kind: ServiceAccount
     name: cicd_installer
 
----
 
+---
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: installer-init-script
+  labels:
+    app: installer
+data:
+  init.sh: |-
+      GOGS_USER=admin
+      GOGS_PWD=admin
+
+      kubectl rollout status deployment/gogs
+
+      _RETURN=$(curl -o /tmp/curl.log -sL --post302 -w "%{http_code}" http://gogs:3000/user/sign_up \
+      --form user_name=$GOGS_USER \
+      --form password=$GOGS_PWD \
+      --form retype=$GOGS_PWD \
+      --form email=admin@gogs.com)
+
+      sleep 5
+
+      if [ $_RETURN != "200" ] && [ $_RETURN != "302" ] ; then
+      echo "ERROR: Failed to create Gogs admin"
+      cat /tmp/curl.log
+      exit 255
+      fi
+
+      sleep 10
+
+      cat <<EOF > /tmp/data.json
+      {
+      "clone_addr": "$$import_repo",
+      "uid": 1,
+      "repo_name": "$$gogs_repo_name"
+      }
+      EOF
+
+      _RETURN=$(curl -o /tmp/curl.log -sL -w "%{http_code}" -H "Content-Type: application/json" \
+      -u $GOGS_USER:$GOGS_PWD -X POST http://gogs:3000/api/v1/repos/migrate -d @/tmp/data.json)
+
+      if [ $_RETURN != "201" ] ;then
+      echo "ERROR: Failed to import repo $$import_repo"
+      cat /tmp/curl.log
+      exit 255
+      fi
+
+
+
+      function disable_outreach() {
+        local _NEXUS_USER=$1
+        local _NEXUS_PWD=$2
+        local _NEXUS_URL=$3
+
+        read -r -d '' _DISABLE_JSON << EOM
+      {
+        "name": "disable_outreach",
+        "type": "groovy",
+        "content": "capabilityRegistry = container.lookup(org.sonatype.nexus.capability.CapabilityRegistry.class)\ncapabilityRegistry.all.findAll {it.context().type().toString().startsWith(\"Outreach\")}.each {\ncapabilityRegistry.disable(it.context().id())\n}"
+      }
+      EOM
+
+        curl -v -H "Accept: application/json" -H "Content-Type: application/json" -d "$_DISABLE_JSON" -u "$_NEXUS_USER:$_NEXUS_PWD" "${_NEXUS_URL}/service/rest/v1/script/"
+        curl -v -X POST -H "Content-Type: text/plain" -u "$_NEXUS_USER:$_NEXUS_PWD" "${_NEXUS_URL}/service/rest/v1/script/disable_outreach/run"
+      }
+
+      function change_admin_password() {
+        local _NEXUS_USER=$1
+        local _NEXUS_PWD=$2
+        local _NEXUS_URL=$3
+
+        read -r -d '' _CHG_PWD_JSON << EOM
+      {
+        "name": "reset_password",
+        "type": "groovy",
+        "content": "security.securitySystem.changePassword('admin','admin')"
+      }
+      EOM
+
+
+        curl -v -H "Accept: application/json" -H "Content-Type: application/json" -d "$_CHG_PWD_JSON" -u "$_NEXUS_USER:$_NEXUS_PWD" "${_NEXUS_URL}/service/rest/v1/script/"
+        curl -v -X POST -H "Content-Type: text/plain" -u "$_NEXUS_USER:$_NEXUS_PWD" "${_NEXUS_URL}/service/rest/v1/script/reset_password/run"
+      }
+
+      disable_outreach admin admin123 'http://nexus:8081'
+      change_admin_password admin admin123 'http://nexus:8081'
+
+      echo 'Installation has completed successfully.'
+
+
+---
 
 apiVersion: batch/v1
 kind: Job
 metadata:
   name: cicd-installer
+  labels:
+    app: installer
 spec:
-  activeDeadlineSeconds: 400
+  activeDeadlineSeconds: 600
   completions: 1
   parallelism: 1
   template:
@@ -36,71 +132,14 @@ spec:
       containers:
         - name: cicd-installer-job
           image: openshift/origin:v3.11
-          resources: {}
-          terminationMessagePath: /dev/termination-log
-          terminationMessagePolicy: File
-          env:
-            - name: CICD_NAMESPACE
-              valueFrom:
-                fieldRef:
-                  fieldPath: metadata.namespace
+          volumeMounts:            
+            - name: init-script
+              mountPath: /var/init-script
           command:
             - /bin/bash
             - -x
-            - -c
-            - |
-
-              # setup dev env
-              oc import-image wildfly --from=openshift/wildfly-120-centos7 --confirm -n ${DEV_PROJECT} 
-
-              # setup image registry
-              # cicd
-              oc create secret generic quay-cicd-secret --from-literal="username=${QUAY_USERNAME}" --from-literal="password=${QUAY_PASSWORD}" -n ${CICD_NAMESPACE}
-              oc label secret quay-cicd-secret credential.sync.jenkins.openshift.io=true -n ${CICD_NAMESPACE}
-              
-              # dev
-              oc create secret docker-registry quay-cicd-secret --docker-server=quay.io --docker-username="${QUAY_USERNAME}" --docker-password="${QUAY_PASSWORD}" --docker-email=cicd@redhat.com -n ${DEV_PROJECT}
-              oc new-build --name=tasks --image-stream=wildfly:latest --binary=true --push-secret=quay-cicd-secret --to-docker --to='quay.io/${QUAY_USERNAME}/${QUAY_REPOSITORY}:latest' -n ${DEV_PROJECT}
-              oc new-app --name=tasks --docker-image=quay.io/${QUAY_USERNAME}/${QUAY_REPOSITORY}:latest --allow-missing-images -n ${DEV_PROJECT}
-              oc set triggers dc tasks --remove-all -n ${DEV_PROJECT}
-              oc patch dc tasks -p '{"spec": {"template": {"spec": {"containers": [{"name": "tasks", "imagePullPolicy": "Always"}]}}}}' -n ${DEV_PROJECT}
-              oc delete is tasks -n ${DEV_PROJECT}
-              oc secrets link default quay-cicd-secret --for=pull -n ${DEV_PROJECT}
-              
-              # stage
-              oc create secret docker-registry quay-cicd-secret --docker-server=quay.io --docker-username="${QUAY_USERNAME}" --docker-password="${QUAY_PASSWORD}" --docker-email=cicd@redhat.com -n ${STAGE_PROJECT}
-              oc new-app --name=tasks --docker-image=quay.io/${QUAY_USERNAME}/${QUAY_REPOSITORY}:stage --allow-missing-images -n ${STAGE_PROJECT}
-              oc set triggers dc tasks --remove-all -n ${STAGE_PROJECT}
-              oc patch dc tasks -p '{"spec": {"template": {"spec": {"containers": [{"name": "tasks", "imagePullPolicy": "Always"}]}}}}' -n ${STAGE_PROJECT}
-              oc delete is tasks -n ${STAGE_PROJECT}
-              oc secrets link default quay-cicd-secret --for=pull -n ${STAGE_PROJECT}
-
-              
-              # dev project
-              oc expose dc/tasks --port=8080 -n ${DEV_PROJECT}
-              oc expose svc/tasks -n ${DEV_PROJECT}
-              oc set probe dc/tasks --readiness --get-url=http://:8080/ws/demo/healthcheck --initial-delay-seconds=30 --failure-threshold=10 --period-seconds=10 -n ${DEV_PROJECT}
-              oc set probe dc/tasks --liveness  --get-url=http://:8080/ws/demo/healthcheck --initial-delay-seconds=180 --failure-threshold=10 --period-seconds=10 -n ${DEV_PROJECT}
-              oc rollout cancel dc/tasks -n ${STAGE_PROJECT}
-
-              # stage project
-              oc expose dc/tasks --port=8080 -n ${STAGE_PROJECT}
-              oc expose svc/tasks -n ${STAGE_PROJECT}
-              oc set probe dc/tasks --readiness --get-url=http://:8080/ws/demo/healthcheck --initial-delay-seconds=30 --failure-threshold=10 --period-seconds=10 -n ${STAGE_PROJECT}
-              oc set probe dc/tasks --liveness  --get-url=http://:8080/ws/demo/healthcheck --initial-delay-seconds=180 --failure-threshold=10 --period-seconds=10 -n ${STAGE_PROJECT}
-              oc rollout cancel dc/tasks -n ${DEV_PROJECT}
-
-
-
-
-
-
-
-
-
-
-              # kubectl rollout status deployment/nexus
-              # NEXUS_POD=$(k get pod -l app=nexus -o=jsonpath='{.items[0].metadata.name}')
-              # kubectl exec ${NEXUS_POD} -- /bin/bash -c 'curl -o /tmp/nexus-functions -s https://raw.githubusercontent.com/OpenShiftDemos/nexus/master/scripts/nexus-functions; source /tmp/nexus-functions; add_nexus3_redhat_repos admin admin123 http://localhost:8081'
-
-
+            - /var/init-script/init.sh
+      volumes:
+        - name: init-script
+          configMap:
+            name: installer-init-script
